spring:
  application.name: api_gateway
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: http://192.168.39.31:30082
          predicates:
            - Path=/api/test-service/**
          filters:
            - AuthFilter

jwt:
  jwk-url: http://192.168.39.31:30085/realms/master/protocol/openid-connect/certs
  issuer: http://192.168.39.31:30085/realms/master